# Generated by Django 4.0.4 on 2022-05-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0003_alter_cities_citi_main_slug_alter_cities_country_and_more'),
        ('Foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryfood',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='Cities.countries'),
        ),
        migrations.AlterField(
            model_name='countryfood',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
