# Generated by Django 4.0.4 on 2022-05-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0004_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryfood',
            name='status',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='Foods.status'),
        ),
    ]
