# Generated by Django 4.0.4 on 2022-05-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0006_alter_countryfood_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryfood',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Foods.status'),
        ),
    ]
