# Generated by Django 4.0.4 on 2022-05-25 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0012_alter_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryfood',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Foods.status'),
        ),
    ]
