# Generated by Django 4.0.4 on 2022-05-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0014_alter_status_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryfood',
            name='status',
        ),
    ]
