# Generated by Django 4.0.4 on 2022-05-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0018_filters_remove_countryfood_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryfood',
            name='filter_by',
        ),
        migrations.AddField(
            model_name='countryfood',
            name='filter_by',
            field=models.ManyToManyField(blank=True, null=True, to='Foods.filters'),
        ),
    ]
