# Generated by Django 4.0.4 on 2022-06-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0019_remove_countryfood_filter_by_countryfood_filter_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryfood',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='countryfood',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
