# Generated by Django 4.0.4 on 2022-06-11 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Countries', '0003_alter_countries_continent'),
        ('Foods', '0020_alter_countryfood_options_countryfood_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryfood',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='Countries.countries'),
        ),
    ]
