# Generated by Django 4.0.4 on 2022-06-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0021_alter_countryfood_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryfood',
            name='filter_by',
            field=models.ManyToManyField(blank=True, to='Foods.filters'),
        ),
    ]
