# Generated by Django 4.0.4 on 2022-06-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0022_alter_countryfood_filter_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryfood',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
