# Generated by Django 4.0.4 on 2022-06-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0023_remove_countryfood_status_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryfood',
            name='filter_by',
            field=models.ManyToManyField(blank=True, default=1, to='Foods.filters'),
        ),
    ]
