# Generated by Django 4.0.4 on 2022-06-18 10:04

import Foods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0024_alter_countryfood_filter_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryfood',
            name='filter_by',
            field=models.ManyToManyField(blank=True, default=Foods.models.get_first_model1, to='Foods.filters'),
        ),
    ]
