# Generated by Django 4.0.4 on 2022-06-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0028_alter_countryfood_filter_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryfood',
            name='filter_by',
            field=models.ManyToManyField(default=1, related_name='filter_foods', to='Foods.filters'),
        ),
    ]
