# Generated by Django 4.0.4 on 2022-06-18 10:44

import Foods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0031_remove_countryfood_filter_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryfood',
            name='filter_by',
            field=models.ManyToManyField(default=Foods.models.get_first_model1, related_name='filter_foods', to='Foods.filters'),
        ),
    ]
