# Generated by Django 4.0.4 on 2022-06-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0037_alter_countryfood_filter_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='filters',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
