# Generated by Django 4.0.4 on 2022-05-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Continents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ListOfCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=85)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('population', models.DecimalField(decimal_places=2, max_digits=6)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('capital', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='capital', to='Cities.listofcities')),
                ('list_cities', models.ManyToManyField(to='Cities.listofcities')),
                ('location', models.ForeignKey(blank=True, default='Asia', on_delete=django.db.models.deletion.CASCADE, to='Cities.continents')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost_of_living', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cities.countries')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cities.listofcities')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_of_air', to='Cities.airstatus')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
