# Generated by Django 4.0.4 on 2022-05-07 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='slug',
            new_name='citi_main_slug',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='slug',
            new_name='country_slug',
        ),
        migrations.RenameField(
            model_name='listofcities',
            old_name='slug',
            new_name='city_slug',
        ),
        migrations.AlterField(
            model_name='countries',
            name='capital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital', to='Cities.listofcities'),
        ),
    ]
