# Generated by Django 4.0.4 on 2022-05-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0002_rename_slug_cities_citi_main_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='citi_main_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='Cities.countries'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_of_city', to='Cities.listofcities'),
        ),
    ]
