# Generated by Django 4.0.4 on 2022-06-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0006_remove_cities_search_remove_countries_search_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'ordering': ('country_slug',)},
        ),
    ]
