# Generated by Django 4.0.4 on 2022-06-11 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0012_alter_cities_name_alter_cities_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='country',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
    ]
