# Generated by Django 4.0.4 on 2022-06-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0013_remove_cities_country_delete_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameModel(
            old_name='AirStatus',
            new_name='AirPorts',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='status',
        ),
        migrations.AddField(
            model_name='cities',
            name='airports',
            field=models.ManyToManyField(blank=True, to='Cities.airports'),
        ),
        migrations.AddField(
            model_name='cities',
            name='area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='crime_rate',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='english_speaking',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='foreign_friendly',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='free_wi_fi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='governor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='population',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='cost_of_living',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='cities',
            name='districts',
            field=models.ManyToManyField(blank=True, to='Cities.districts'),
        ),
    ]
