version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn backend.wsgi:application -b 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/back/web/staticfiles
      - media_volume:/home/back/web/media
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    image: jonasal/nginx-certbot:latest
    env_file:
      - .env.nginx
    ports:
     - 80:80
     - 443:443
    volumes:
      - static_volume:/home/back/web/staticfiles
      - media_volume:/home/back/web/media
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d
    depends_on:
     - web

volumes:
  static_volume:
  media_volume:
  nginx_secrets:

