# Generated by Django 4.0.4 on 2022-05-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0006_remove_cities_search_remove_countries_search_and_more'),
        ('EatPlace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatplaces',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eat_places', to='Cities.listofcities'),
        ),
    ]
