# Generated by Django 4.0.4 on 2022-05-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EatPlace', '0002_alter_eatplaces_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
