# Generated by Django 4.0.4 on 2022-05-26 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EatPlace', '0003_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatplaces',
            name='filter_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EatPlace.filters'),
        ),
    ]
