# Generated by Django 4.0.4 on 2022-05-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EatPlace', '0005_remove_eatplaces_filter_by_eatplaces_filter_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatplaces',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
