# Generated by Django 4.0.4 on 2022-06-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EatPlace', '0006_alter_eatplaces_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eatplaces',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='eatplaces',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
