# Generated by Django 4.0.4 on 2022-06-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EatPlace', '0007_alter_eatplaces_options_eatplaces_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatplaces',
            name='filter_by',
            field=models.ManyToManyField(blank=True, to='EatPlace.filters'),
        ),
    ]
