# Generated by Django 4.0.4 on 2022-06-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EatPlace', '0008_alter_eatplaces_filter_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='filters',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
