# Generated by Django 4.0.4 on 2022-05-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0003_rent_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='name',
            new_name='name_of_company',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='company',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='url_of_rent',
        ),
        migrations.AddField(
            model_name='rent',
            name='apartment',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='rent',
            name='guest_house',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='rent',
            name='hotel',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='rent',
            name='house',
            field=models.URLField(default=''),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
