# Generated by Django 4.0.4 on 2022-06-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0006_alter_rent_options_rent_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, default='')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.RemoveField(
            model_name='rent',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='guest_house',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='house',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='rent',
            name='filter_by',
            field=models.ManyToManyField(blank=True, default=1, to='Rent.filters'),
        ),
    ]
