# Generated by Django 4.0.4 on 2022-06-19 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0007_filters_remove_rent_apartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filters',
            name='url',
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_to_recognize', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, default='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Rent.filters')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.AddField(
            model_name='rent',
            name='list_urls',
            field=models.ManyToManyField(default=1, to='Rent.url'),
        ),
    ]
