# Generated by Django 4.0.4 on 2022-06-19 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0008_remove_filters_url_url_rent_list_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='english_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='url',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent.filters'),
        ),
    ]
