# Generated by Django 4.0.4 on 2022-06-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Z_Meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metatag',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='metatag',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
