# Generated by Django 4.0.4 on 2022-06-11 06:51

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('Cities', '0010_remove_countries_capital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('population', models.DecimalField(decimal_places=2, max_digits=6)),
                ('country_slug', models.SlugField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('capital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital', to='Cities.listofcities')),
                ('list_cities', models.ManyToManyField(to='Cities.listofcities')),
                ('location', models.ForeignKey(blank=True, default='Asia', on_delete=django.db.models.deletion.CASCADE, to='Cities.continents')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
