# Generated by Django 4.0.4 on 2022-06-11 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0010_remove_countries_capital_and_more'),
        ('Countries', '0002_rename_location_countries_continent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='continent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Cities.continents'),
        ),
    ]
