# Generated by Django 4.0.4 on 2022-06-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Countries', '0003_alter_countries_continent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Religions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='countries',
            name='climate',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='flag_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/flags/'),
        ),
        migrations.AddField(
            model_name='countries',
            name='foreign_friendly',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='independence_day',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='life_expectency',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='literacy_rate',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='main_language',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='number_of_foreigners',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='number_of_state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='popular_foreign_langs',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='population',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='president',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_near_flag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='airports',
            field=models.ManyToManyField(blank=True, to='Countries.airports'),
        ),
        migrations.AddField(
            model_name='countries',
            name='seasons',
            field=models.ManyToManyField(blank=True, to='Countries.seasons'),
        ),
    ]
