# Generated by Django 4.0.4 on 2022-06-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Countries', '0004_airports_religions_seasons_countries_climate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Religions',
        ),
        migrations.AlterField(
            model_name='countries',
            name='independence_day',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
