# Generated by Django 4.0.4 on 2022-06-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Countries', '0006_airports_airport_slug_seasons_season_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airports',
            name='airport_slug',
        ),
        migrations.RemoveField(
            model_name='seasons',
            name='season_slug',
        ),
    ]
