# Generated by Django 4.0.4 on 2022-05-11 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0003_alter_cities_citi_main_slug_alter_cities_country_and_more'),
        ('Score', '0004_rename_quality_of_lie_score_quality_of_life_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='Cities.listofcities'),
        ),
    ]
