# Generated by Django 4.0.4 on 2022-05-12 18:24

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('Score', '0005_alter_score_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
