# Generated by Django 4.0.4 on 2022-05-25 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0003_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='district',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Visit.district'),
        ),
    ]
