# Generated by Django 4.0.4 on 2022-05-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0004_visit_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='best_time_togo',
        ),
    ]
