# Generated by Django 4.0.4 on 2022-05-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0005_remove_visit_best_time_togo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='entry_fee',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
