# Generated by Django 4.0.4 on 2022-06-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0006_alter_visit_entry_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='visit',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
