# Generated by Django 4.0.4 on 2022-06-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0007_alter_visit_options_visit_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.RemoveField(
            model_name='visit',
            name='tags',
        ),
        migrations.DeleteModel(
            name='FilterBy',
        ),
        migrations.AddField(
            model_name='visit',
            name='filter_by',
            field=models.ManyToManyField(default=1, related_name='filter_foods', to='Visit.filters'),
        ),
    ]
