# Generated by Django 4.0.4 on 2022-06-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0008_alter_cities_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='cities',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='countries',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
