# Generated by Django 4.0.4 on 2022-06-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0009_alter_cities_options_alter_countries_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='list_cities',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='location',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='population',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='tag',
        ),
    ]
