# Generated by Django 4.0.4 on 2022-06-11 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0010_remove_countries_capital_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={},
        ),
        migrations.RemoveField(
            model_name='countries',
            name='order',
        ),
        migrations.AlterField(
            model_name='cities',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cities.countries'),
        ),
    ]
