# Generated by Django 4.0.4 on 2022-06-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0010_remove_countries_capital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='country',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
    ]
