# Generated by Django 4.0.4 on 2022-06-11 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0011_alter_countries_options_remove_countries_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_of_city_1', to='Cities.listofcities'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_of_air_1', to='Cities.airstatus'),
        ),
    ]
