# Generated by Django 4.0.4 on 2022-06-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMAGES', '0003_images_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='images',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
