# Generated by Django 4.0.4 on 2022-06-11 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Countries', '0003_alter_countries_continent'),
        ('IMAGES', '0004_alter_images_options_images_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_images', to='Countries.countries'),
        ),
    ]
