# Generated by Django 4.0.4 on 2022-06-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('comments', models.IntegerField(default=0)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['comments'],
            },
        ),
    ]
