# Generated by Django 4.0.4 on 2022-05-11 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cities', '0003_alter_cities_citi_main_slug_alter_cities_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostOfLiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('water', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coffee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dinner', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lunch', models.DecimalField(decimal_places=2, max_digits=12)),
                ('breakfast', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cheapest_meal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coke', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bigmac_index', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mid_restaurant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('city', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cost_of_living', to='Cities.listofcities')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
