# Generated by Django 4.0.4 on 2022-05-11 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0003_alter_cities_citi_main_slug_alter_cities_country_and_more'),
        ('CostOfLiving', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costofliving',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_of_living', to='Cities.listofcities'),
        ),
    ]
