# Generated by Django 4.0.4 on 2022-05-26 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0006_remove_cities_search_remove_countries_search_and_more'),
        ('CostOfLiving', '0004_costofliving_apples_costofliving_beef_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_of_living_2', to='Cities.listofcities')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
