# Generated by Django 4.0.4 on 2022-06-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CostOfLiving', '0006_alter_costofliving_apples_alter_costofliving_beef_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costofliving',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='costofliving',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
