# Generated by Django 4.0.4 on 2022-06-19 09:32

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('CostOfLiving', '0007_alter_costofliving_options_costofliving_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costs',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='costs',
            name='filter_by',
            field=models.ManyToManyField(blank=True, to='CostOfLiving.filters'),
        ),
        migrations.AddField(
            model_name='costs',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='costs',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='costs',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='filters',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CostOfLiving',
        ),
    ]
