# Generated by Django 4.0.4 on 2022-06-18 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Countries', '0007_remove_airports_airport_slug_and_more'),
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonapps',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps_in_ct', to='Countries.countries'),
        ),
    ]
