# Generated by Django 4.0.4 on 2022-05-11 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0003_countryapps_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryapps',
            name='slug',
            field=models.SlugField(blank=True, default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Cities.countries')),
        ),
    ]
