# Generated by Django 4.0.4 on 2022-05-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0004_alter_countryapps_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryapps',
            name='search',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
