# Generated by Django 4.0.4 on 2022-05-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0008_filters_commonapps_url_commonapps_filter_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonapps',
            name='filter_by',
        ),
        migrations.AddField(
            model_name='commonapps',
            name='filter_by',
            field=models.ManyToManyField(blank=True, null=True, to='Apps.filters'),
        ),
    ]
