# Generated by Django 4.0.4 on 2022-05-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0009_remove_commonapps_filter_by_commonapps_filter_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonapps',
            name='description',
            field=models.TextField(max_length=35),
        ),
    ]
