# Generated by Django 4.0.4 on 2022-06-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0013_alter_countryapps_country_alter_countryapps_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonapps',
            name='filter_by',
            field=models.ManyToManyField(blank=True, to='Apps.filters'),
        ),
    ]
