# Generated by Django 4.0.4 on 2022-05-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cities', '0003_alter_cities_citi_main_slug_alter_cities_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('book', models.CharField(blank=True, max_length=1000)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='Cities.countries')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_status', to='Transport.transportstatus')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
