# Generated by Django 4.0.4 on 2022-05-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0003_transport_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='book',
        ),
        migrations.AlterField(
            model_name='transport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
