# Generated by Django 4.0.4 on 2022-06-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0004_remove_transport_book_alter_transport_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='transport',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
