# Generated by Django 4.0.4 on 2022-06-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0006_alter_transport_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.RemoveField(
            model_name='transport',
            name='status',
        ),
        migrations.DeleteModel(
            name='TransportStatus',
        ),
        migrations.AddField(
            model_name='transport',
            name='filter_by',
            field=models.ManyToManyField(related_name='transport_filter', to='Transport.filters'),
        ),
    ]
